
import pandas as pd
import argparse
import os
import sys
from typing import Dict, Optional, Tuple

def calculate_otp_score(
    otp_csv_path: str, 
    filter_column: str = "arrDelay", 
    min_threshold: float = -180.0, 
    max_threshold: float = 180.0
) -> Dict[str, any]:
    """
    Calculates On-Time Performance (OTP) score based on prepared OTP data.
    
    Args:
        otp_csv_path (str): Path to the CSV file generated by OnTimePerformancePrepareData.
        filter_column (str): The column to filter on (e.g., 'arrDelay', 'depDelay').
        min_threshold (float): Minimum acceptable value (inclusive).
        max_threshold (float): Maximum acceptable value (inclusive).
        
    Returns:
        Dict: Dictionary containing:
            - 'total_records': Total number of records processed.
            - 'on_time_records': Number of records within the threshold.
            - 'otp_percentage': Percentage of on-time records.
    """
    print(f"[OTP Scoring] Loading data from: {otp_csv_path}")
    if not os.path.exists(otp_csv_path):
        print(f"Error: File not found at {otp_csv_path}")
        return {"total_records": 0, "on_time_records": 0, "otp_percentage": 0.0}
        
    try:
        df = pd.read_csv(otp_csv_path)
        
        if filter_column not in df.columns:
            print(f"Error: Column '{filter_column}' not found in {otp_csv_path}")
            print(f"Available columns: {list(df.columns)}")
            return {"total_records": 0, "on_time_records": 0, "otp_percentage": 0.0}
            
        # Ensure column is numeric
        df[filter_column] = pd.to_numeric(df[filter_column], errors='coerce').fillna(0.0)
        
        total_records = len(df)
        
        # Filter Logic: min <= value <= max
        on_time_df = df[
            (df[filter_column] >= min_threshold) & 
            (df[filter_column] <= max_threshold)
        ]
        
        on_time_count = len(on_time_df)
        percentage = (on_time_count / total_records * 100) if total_records > 0 else 0.0
        
        return {
            "total_records": total_records,
            "on_time_records": on_time_count,
            "otp_percentage": percentage
        }
        
    except Exception as e:
        print(f"Error calculating OTP score: {e}")
        return {"total_records": 0, "on_time_records": 0, "otp_percentage": 0.0}


if __name__ == "__main__":
    pass
