
import pandas as pd
import argparse
import os
import sys
from typing import Dict

def calculate_travel_time_scores(ridership_csv_path: str) -> Dict[str, float]:
    """
    Calculates total travel time for Car and Bus trips based on prepared ridership data.
    
    Args:
        ridership_csv_path (str): Path to the CSV file generated by RidershipPrepareData.
        
    Returns:
        Dict[str, float]: Dictionary containing:
            - 'total_car_travel_time': Sum of travel time for mainMode == 'car'
            - 'total_bus_travel_time': Sum of travel time for mainMode == 'pt' AND vehTypeList contains 'bus'
    """
    print(f"[Travel Time Scoring] Loading data from: {ridership_csv_path}")
    if not os.path.exists(ridership_csv_path):
        print(f"Error: File not found at {ridership_csv_path}")
        return {"total_car_travel_time": 0.0, "total_bus_travel_time": 0.0}
        
    try:
        df = pd.read_csv(ridership_csv_path)
        
        required_cols = ['mainMode', 'travelTime', 'vehTypeList']
        for col in required_cols:
            if col not in df.columns:
                print(f"Error: Missing required column '{col}' in {ridership_csv_path}")
                return {"total_car_travel_time": 0.0, "total_bus_travel_time": 0.0}
                
        # Fill NA
        df['mainMode'] = df['mainMode'].fillna('').astype(str)
        df['vehTypeList'] = df['vehTypeList'].fillna('').astype(str)
        df['travelTime'] = pd.to_numeric(df['travelTime'], errors='coerce').fillna(0.0)

        # 1. Total Car Travel Time
        # Condition: mainMode == 'car'
        car_trips = df[df['mainMode'] == 'car']
        total_car_time = car_trips['travelTime'].sum()
        
        # 2. Total Bus Travel Time
        # Usually implies mainMode='pt' or just any trip using a bus? 
        # Requirement: "main mode pt và type có chứa string bus"
        # So condition: mainMode == 'pt' AND vehTypeList contains 'bus'
        bus_trips = df[
            (df['mainMode'] == 'pt') & 
            (df['vehTypeList'].str.contains("bus", case=False))
        ]
        total_bus_time = bus_trips['travelTime'].sum()
        
        print(f"[Travel Time Scoring] Car Trips: {len(car_trips)}, Total Time: {total_car_time}")
        print(f"[Travel Time Scoring] Bus Trips: {len(bus_trips)}, Total Time: {total_bus_time}")
        
        return {
            "total_car_travel_time": float(total_car_time),
            "total_bus_travel_time": float(total_bus_time)
        }
        
    except Exception as e:
        print(f"Error calculating travel time scores: {e}")
        return {"total_car_travel_time": 0.0, "total_bus_travel_time": 0.0}

def main():
    parser = argparse.ArgumentParser(description="Calculate Travel Time Scores")
    parser.add_argument("--ridership_csv", required=True, help="Path to the prepared ridership CSV file")
    args = parser.parse_args()
    
    scores = calculate_travel_time_scores(args.ridership_csv)
    print(f"RESULT={scores}")

if __name__ == "__main__":
    main()
